version: "3"
services:
  test:
    build: .
    command: "npx tape dist/**/*spec.js"
    env_file: .env
    links:
      - "test-postgres:data"
    volumes:
      - ".:/app"
      - "dependencies:/app/node_modules"
  test-postgres:
    image: postgres:10.6-alpine
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=cala"
    volumes:
      - "test-data:/var/lib/postgresql/data"

volumes:
  test-data:
