#!/bin/bash
set -e

main() {
  app=${1:-""}

  if [ "$app" == "" ]; then
      echo "Usage: migrate-prod [heroku app name]"
      exit 1
  fi

  if [[ $(git rev-parse --abbrev-ref HEAD) != "master" ]] ; then
    echo 'Cannot run stg/prod migrations from a branch other than master'
    exit 1
  fi

  if [[ $(git status --porcelain) != '' ]] ; then
    echo 'Cannot migrate with uncommitted changes'
    exit 1
  fi

  if [[ $(git cherry -v origin/master) != "" ]]; then
    echo 'Cannot migrate with unpushed commits'
    exit 1
  fi

  echo "Are you sure you want to migrate the PRODUCTION db?"
  echo -n "Type PRODUCTION if you're sure: "
  read RES

  if [ "$RES" != "PRODUCTION" ]; then
    echo "OK, not migrating"
    exit 1
  fi

  DATABASE_URL=$(heroku config:get DATABASE_URL --app "$app"-prod)?ssl=true $(npm bin)/knex migrate:latest
}

main "$@"
