#!/bin/bash
set -e

main() {
  app=${1:-""}

  if [ "$app" == "" ]; then
    echo "Usage: migrate-stg [heroku app name]"
    exit 1
  fi

  if [[ $(git rev-parse --abbrev-ref HEAD) != "master" ]] ; then
    echo 'Cannot run stg/prod migrations from a branch other than master'
    exit 1
  fi

  if [[ $(git status --porcelain) != '' ]] ; then
    echo 'Cannot migrate with uncommitted changes'
    exit 1
  fi

  if [[ $(git cherry -v origin/master) != "" ]]; then
    echo 'Cannot migrate with unpushed commits'
    exit 1
  fi

  if [[ "$1" != "--force" ]]; then
    echo "Are you sure you want to migrate the STAGING db?"
    echo -n "Type STAGING if you're sure: "
    read RES

    if [ "$RES" != "STAGING" ]; then
      echo "OK, not migrating"
      exit 1
    fi
  fi

  DATABASE_URL=$(heroku config:get DATABASE_URL --app "$app"-stg)?ssl=true $(npm bin)/knex migrate:latest
}

main "$@"
