import { z } from "zod";

export enum Complexity {
  BLANK = "BLANK",
  SIMPLE = "SIMPLE",
  MEDIUM = "MEDIUM",
  COMPLEX = "COMPLEX",
}

export enum ProcessComplexity {
  SIMPLE = "SIMPLE",
  MEDIUM = "MEDIUM",
  COMPLEX = "COMPLEX",
}

export enum MaterialCategory {
  SPECIFY = "SPECIFY",
  BASIC = "BASIC",
  STANDARD = "STANDARD",
  LUXE = "LUXE",
  ULTRA_LUXE = "ULTRA_LUXE",
}

export enum ScreenPrintingComplexity {
  "1_COLOR" = "1_COLOR",
  "2_COLORS" = "2_COLORS",
  "3_COLORS" = "3_COLORS",
  "4_COLORS" = "4_COLORS",
  "5_COLORS" = "5_COLORS",
  "6_COLORS" = "6_COLORS",
  "7_COLORS" = "7_COLORS",
  "8_COLORS" = "8_COLORS",
  "9_COLORS" = "9_COLORS",
  "10_COLORS" = "10_COLORS",
  "11_COLORS" = "11_COLORS",
}

export enum ProcessSizeComplexity {
  "SMALL" = "SMALL",
  "MEDIUM" = "MEDIUM",
  "LARGE" = "LARGE",
}

export const processSchema = z.union([
  z.object({
    name: z.literal("CUSTOM_METAL_HARDWARE"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
  z.object({
    name: z.literal("DISTRESS"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
  z.object({
    name: z.literal("DTG_PRINT"),
    complexity: z.nativeEnum(ProcessSizeComplexity),
  }),
  z.object({
    name: z.literal("DYE"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
  z.object({
    name: z.literal("EMBELLISH"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
  z.object({
    name: z.literal("EMBROIDERY"),
    complexity: z.nativeEnum(ProcessSizeComplexity),
  }),
  z.object({
    name: z.literal("FABRIC_PRINT"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
  z.object({
    name: z.literal("LABEL_APPLICATION"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
  z.object({
    name: z.literal("PLEATING"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
  z.object({
    name: z.literal("SCREEN_PRINT"),
    complexity: z.nativeEnum(ScreenPrintingComplexity),
  }),
  z.object({
    name: z.literal("SCREEN_PRINT_PROCESS"),
    complexity: z.literal("PUFF or FOIL or REFLECTIVE"),
  }),
  z.object({
    name: z.literal("WASH"),
    complexity: z.nativeEnum(ProcessComplexity),
  }),
]);

export type Process = z.infer<typeof processSchema>;

export function isProcess(candidate: object): candidate is Process {
  const keyset = new Set(Object.keys(candidate));
  return ["name", "complexity"].every(keyset.has.bind(keyset));
}

export enum ProductType {
  "ACCESSORIES - BACKPACK" = "ACCESSORIES - BACKPACK",
  "ACCESSORIES - BANDANNA" = "ACCESSORIES - BANDANNA",
  "ACCESSORIES - BASEBALL CAP" = "ACCESSORIES - BASEBALL CAP",
  "ACCESSORIES - BUCKET HAT" = "ACCESSORIES - BUCKET HAT",
  "ACCESSORIES - CUT + SEW SCARF" = "ACCESSORIES - CUT + SEW SCARF",
  "ACCESSORIES - FULLY FASHIONED BEANIE" = "ACCESSORIES - FULLY FASHIONED BEANIE",
  "ACCESSORIES - GLOVES" = "ACCESSORIES - GLOVES",
  "ACCESSORIES - JACQURD KNIT SCARF" = "ACCESSORIES - JACQURD KNIT SCARF",
  "ACCESSORIES - KEYCHAIN" = "ACCESSORIES - KEYCHAIN",
  "ACCESSORIES - LARGE BAG" = "ACCESSORIES - LARGE BAG",
  "ACCESSORIES - MEDIUM BAG" = "ACCESSORIES - MEDIUM BAG",
  "ACCESSORIES - MOUTH MASK" = "ACCESSORIES - MOUTH MASK",
  "ACCESSORIES - PHONE CASE" = "ACCESSORIES - PHONE CASE",
  "ACCESSORIES - PRINTED TOWEL" = "ACCESSORIES - PRINTED TOWEL",
  "ACCESSORIES - PURSE" = "ACCESSORIES - PURSE",
  "ACCESSORIES - SMALL BAG" = "ACCESSORIES - SMALL BAG",
  "ACCESSORIES - SUNGLASSES" = "ACCESSORIES - SUNGLASSES",
  "ACCESSORIES - TIE" = "ACCESSORIES - TIE",
  "ACCESSORIES - WALLET" = "ACCESSORIES - WALLET",
  "ACCESSORIES - YARN DYE TOWEL" = "ACCESSORIES - YARN DYE TOWEL",
  "ATHLETIC SHORTS" = "ATHLETIC SHORTS",
  "BACKPACK" = "BACKPACK",
  "BATHROBE" = "BATHROBE",
  "BEANIE" = "BEANIE",
  "BLAZER" = "BLAZER",
  "BLOUSE" = "BLOUSE",
  "BODYSUIT" = "BODYSUIT",
  "BOTTOMS - ATHLETIC SHORTS" = "BOTTOMS - ATHLETIC SHORTS",
  "BOTTOMS - BIKE SHORTS" = "BOTTOMS - BIKE SHORTS",
  "BOTTOMS - DENIM PANTS" = "BOTTOMS - DENIM PANTS",
  "BOTTOMS - DRESS PANTS" = "BOTTOMS - DRESS PANTS",
  "BOTTOMS - JUMPSUIT" = "BOTTOMS - JUMPSUIT",
  "BOTTOMS - LEGGING" = "BOTTOMS - LEGGING",
  "BOTTOMS - MAXI SKIRT" = "BOTTOMS - MAXI SKIRT",
  "BOTTOMS - SHORTS" = "BOTTOMS - SHORTS",
  "BOTTOMS - SKIRT" = "BOTTOMS - SKIRT",
  "BOTTOMS - SWEATPANTS" = "BOTTOMS - SWEATPANTS",
  "BOTTOMS - WOVEN PANTS" = "BOTTOMS - WOVEN PANTS",
  "BRA" = "BRA",
  "BRALETTE" = "BRALETTE",
  "BUCKET HAT" = "BUCKET HAT",
  "CASUAL JACKET" = "CASUAL JACKET",
  "COAT" = "COAT",
  "DENIM JACKET" = "DENIM JACKET",
  "DRESS" = "DRESS",
  "DRESSES - KNIT DRESS" = "DRESSES - KNIT DRESS",
  "DRESSES - WOVEN DRESS" = "DRESSES - WOVEN DRESS",
  "DRESS SHIRT" = "DRESS SHIRT",
  "GLOVES" = "GLOVES",
  "HAT" = "HAT",
  "HOODED SWEATSHIRT" = "HOODED SWEATSHIRT",
  "INTIMATES - BATHROBE" = "INTIMATES - BATHROBE",
  "INTIMATES - BODYSUIT" = "INTIMATES - BODYSUIT",
  "INTIMATES - BRA" = "INTIMATES - BRA",
  "INTIMATES - BRALETTE" = "INTIMATES - BRALETTE",
  "INTIMATES - SOCKS" = "INTIMATES - SOCKS",
  "INTIMATES - UNDERWEAR" = "INTIMATES - UNDERWEAR",
  "JACKET" = "JACKET",
  "JEWELRY - ACRYLIC JEWELRY." = "JEWELRY - ACRYLIC JEWELRY.",
  "JEWELRY - CAST METAL JEWELRY" = "JEWELRY - CAST METAL JEWELRY",
  "LARGE BAG" = "LARGE BAG",
  "LONG SKIRT" = "LONG SKIRT",
  "LONGSLEEVE TEESHIRT" = "LONGSLEEVE TEESHIRT",
  "MAXI SKIRT" = "MAXI SKIRT",
  "MEDIUM BAG" = "MEDIUM BAG",
  "ONE PIECE BATHING SUIT" = "ONE PIECE BATHING SUIT",
  "OTHER - HANGTAGS" = "OTHER - HANGTAGS",
  "OTHER - NOVELTY LABELS" = "OTHER - NOVELTY LABELS",
  "OTHER - PACKAGING" = "OTHER - PACKAGING",
  "OUTERWEAR - CASUAL JACKET" = "OUTERWEAR - CASUAL JACKET",
  "OUTERWEAR - COAT" = "OUTERWEAR - COAT",
  "OUTERWEAR - DENIM JACKET" = "OUTERWEAR - DENIM JACKET",
  "OUTERWEAR - PONCHO" = "OUTERWEAR - PONCHO",
  "OUTERWEAR - PUFFER JACKET" = "OUTERWEAR - PUFFER JACKET",
  "OUTERWEAR - TAILORED JACKET" = "OUTERWEAR - TAILORED JACKET",
  "PACKAGING" = "PACKAGING",
  "PANTS" = "PANTS",
  "POLO/RUGBY SHIRT" = "POLO/RUGBY SHIRT",
  "PONCHO" = "PONCHO",
  "PURSE" = "PURSE",
  "SCARF" = "SCARF",
  "SHORTS" = "SHORTS",
  "SHORTSLEEVE DRESS SHIRT" = "SHORTSLEEVE DRESS SHIRT",
  "SKIRT" = "SKIRT",
  "SMALL BAG" = "SMALL BAG",
  "SOCKS" = "SOCKS",
  "SPORT COAT" = "SPORT COAT",
  "STRUCTURED JUMPSUIT" = "STRUCTURED JUMPSUIT",
  "SUNGLASSES" = "SUNGLASSES",
  "SWEATER" = "SWEATER",
  "SWEATPANTS" = "SWEATPANTS",
  "SWEATSHIRT" = "SWEATSHIRT",
  "SWIMWEAR - ONE PIECE BATHING SUIT" = "SWIMWEAR - ONE PIECE BATHING SUIT",
  "SWIMWEAR - TWO PIECE BATHING SUIT" = "SWIMWEAR - TWO PIECE BATHING SUIT",
  "TAILORED JACKET" = "TAILORED JACKET",
  "TANK TOP" = "TANK TOP",
  "TEESHIRT" = "TEESHIRT",
  "TIE" = "TIE",
  "TOPCOAT" = "TOPCOAT",
  "TOPS - BLOUSE" = "TOPS - BLOUSE",
  "TOPS - DRESS SHIRT" = "TOPS - DRESS SHIRT",
  "TOPS - HOODED SWEATSHIRT" = "TOPS - HOODED SWEATSHIRT",
  "TOPS - LONGSLEEVE TEESHIRT" = "TOPS - LONGSLEEVE TEESHIRT",
  "TOPS - POLO/RUGBY SHIRT" = "TOPS - POLO/RUGBY SHIRT",
  "TOPS - SHORTSLEEVE DRESS SHIRT" = "TOPS - SHORTSLEEVE DRESS SHIRT",
  "TOPS - SWEATER" = "TOPS - SWEATER",
  "TOPS - SWEATSHIRT" = "TOPS - SWEATSHIRT",
  "TOPS - TANK TOP" = "TOPS - TANK TOP",
  "TOPS - TEESHIRT" = "TOPS - TEESHIRT",
  "TWO PIECE BATHING SUIT" = "TWO PIECE BATHING SUIT",
  "UNDERWEAR" = "UNDERWEAR",
  "WALLET" = "WALLET",
  "WOVEN DRESS" = "WOVEN DRESS",
}

export const validProductTypes = Object.values(ProductType);
