version: 2
jobs:
  build:
    environment:
      DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test

    docker:
      - image: circleci/node:10.15.0
      - image: postgres:10.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          paths:
            - "$HOME/.npm"
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - store_test_results:
          path: ~/repo/reports
      - store_artifacts:
          path: ~/repo/reports

      - run: bin/ci-check

      - deploy:
          name: Deploy to Heroku
          command: |
            git config --global user.email "devops@ca.la"
            git config --global user.name "CALA Machine User"

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/publish staging
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              bin/publish production
            fi
