version: 2
jobs:
  build:
    environment:
      DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test

    docker:
      - image: circleci/node:8.2.1
      - image: postgres:9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: make lint-ci
      - run: make build
      - run: bin/migrate local && bin/migrate local rollback && bin/migrate local
      - run:
          command: make test-ci
          when: always
      - store_test_results:
          path: ~/repo/reports
      - store_artifacts:
          path: ~/repo/reports
      - deploy:
          name: Deploy to Heroku
          command: |
            git config --global user.email "devops@ca.la"
            git config --global user.name "CALA Machine User"

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make publish-stg
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              make publish-prod
            fi
