version: 2
jobs:
  build:
    environment:
      DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test

    docker:
      - image: circleci/node:10.15.0
      - image: circleci/postgres:10.6-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          paths:
            - "~/.npm"
          key: v3-dependencies-{{ checksum "package-lock.json" }}

      - run: bin/ci_check

      - store_test_results:
          path: ~/repo/reports
      - store_artifacts:
          path: ~/repo/reports

      - deploy:
          name: Deploy to Heroku
          command: |
            git config --global user.email "devops@ca.la"
            git config --global user.name "CALA Machine User"

            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              bin/publish staging
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              bin/publish production
            fi
